on:
  create:
  issues:
    types: [opened]
  pull_request:
    types: [closed]

jobs:
  foobar:
    name: Foobar
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_EVENT: ${{ toJSON(github.event) }}
        run: echo "$GITHUB_EVENT"
